// Generated by Wrangler - do not edit manually
// Run `npm run cf-typegen` to regenerate

interface Env {
  AI: Ai;
  RATE_LIMIT_KV: KVNamespace;
  CHAT_MINUTE_LIMITER: RateLimit;
  CONTACT_MINUTE_LIMITER: RateLimit;
  ALLOWED_ORIGIN: string;
  AI_MODEL: string;
  CONTACT_TO_EMAIL: string;
  CONTACT_FROM_EMAIL: string;
  EMAIL?: any;
  ENVIRONMENT?: string;
}
