// Generated by Wrangler by running `wrangler types` — manual sync for native rate limits
// Canonical Env shape in src/config.ts — keep synced when adding bindings/vars (period 60s, hour/day as conservative limits)

interface Env {
	ALLOWED_ORIGIN: string;
	AI_MODEL: string;
	EMAIL: SendEmail;
	AI: Ai;
	CHAT_RATE_LIMIT: RateLimit;
	CHAT_RATE_LIMIT_HOUR: RateLimit;
	CHAT_RATE_LIMIT_DAY: RateLimit;
	CONTACT_RATE_LIMIT: RateLimit;
	CONTACT_RATE_LIMIT_HOUR: RateLimit;
	CONTACT_RATE_LIMIT_DAY: RateLimit;
}
